version: "3.9"

services:
  llama-api:
    build: .
    container_name: llama-api
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - ./models:/app/models
    command: bash start.sh

  nginx:
    image: nginx:latest
    container_name: llama-nginx
    depends_on:
      - llama-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: ""
    command: > 
      sh -c "certbot certonly --webroot -w /var/www/certbot 
      --email oracle69digital@gmail.com 
      -d oracle69.com 
      --agree-tos --non-interactive"
