import React, { useState } from 'react';

const App = () => {
  const [input, setInput] = useState('');
  const [html, setHtml] = useState('');
  const [loading, setLoading] = useState(false);

  const handleBuild = () => {
    setLoading(true);
    setTimeout(() => {
      const generated = `
        <html>
          <head><title>${input}</title></head>
          <body>
            <h1>${input}</h1>
            <p>Generated by AI</p>
          </body>
        </html>`;
      setHtml(generated);
      setLoading(false);
    }, 1500);
  };

  const exportHTML = () => {
    const blob = new Blob([html], { type: 'text/html' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'ai-site.html';
    link.click();
  };

  return (
    <div style={{ padding: '2rem', fontFamily: 'Arial' }}>
      <h2>AI Website Builder</h2>
      <input
        type="text"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        placeholder="Enter your business idea"
        style={{ width: '60%', padding: '0.5rem' }}
      />
      <button onClick={handleBuild} style={{ marginLeft: '1rem', padding: '0.5rem 1rem' }}>
        Build
      </button>

      {loading && <p>Generating your site...</p>}

      {html && (
        <>
          <h3>Preview:</h3>
          <iframe srcDoc={html} style={{ width: '100%', height: '300px' }}></iframe>
          <button onClick={exportHTML} style={{ marginTop: '1rem', padding: '0.5rem 1rem' }}>
            Export HTML
          </button>
        </>
      )}
    </div>
  );
};

export default App;
